# -*- coding: utf-8 -*-
"""getdatamL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UUbqKP74v20e6D3kHJj55dODYqeX7Yt-
"""

import numpy as np
import pandas as pd
import seaborn as sns

dataset = sns.load_dataset("titanic")

dataset.head()

dataset["fare"].value_counts(normalize=True)

dataset["fare"].hist()

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

